export default {
  HOME_SCREEN: 'HomeScreen',
  OFFER_RIDES_OR_EDIT_RIDES_SCREEN: 'OfferOrEditRidesScreen',
  CHAT_SCREEN: 'ChatScreen',
  LOGIN_SCREEN: 'LoginScreen',
  REGISTER_SCREEN: 'RegisterScreen',
  RIDES_SCREEN: 'RidesScreen',
  WELCOME_SCREEN: 'WelcomeScreen',
  PROFILE_SCREEN: 'ProfileScreen',
  SEARCH_RIDE_SCREEN: 'SearchRideScreen',
  SEARCH_RIDE_ORIGIN_SCREEN: 'SearchRideOriginScreen',
  SEARCH_RIDE_DESTINATION_SCREEN: 'SearchRideDestinationScreen',
  RIDE_SCREEN: 'RideScreen',
  CONVERSATION_SCREEN: 'ConversationScreen',
  EDIT_RIDE_SCREEN: 'EditRideScreen',
  OFFERING_PROFILE_SCREEN: 'OfferingProfileScreen',
  EDIT_PROFILE_SCREEN: 'EditProfileScreen',
  SETTINGS_SCREEN: 'SettingsScreen',
  ABOUT_SCREEN: 'AboutScreen',
  LANGUAGE_SCREEN: 'LanguageScreen',
  GROUPS_SCREEN: 'GroupsScreen',
};
